/**
 * @file	mazda_z5.cpp
 *
 * @date Nov 16, 2018
 * @author Andrey Belomutskiy, (c) 2012-2018
 * @author Alexander Wilhelmi, (c) 2018
 */

#include "mazda_z5.h"
#include "global.h"
#include "settings.h"
#include "allsensors.h"
#include "engine_math.h"
#include "rusefi_enums.h"
#include "thermistors.h"
#include "custom_engine.h"



EXTERN_ENGINE;


static const ignition_table_t mazda_z5_ign_advance_table={
/* Generated by pytools/TS-ign-table_to_c-code.py on Wed Dec 12 12:28:56 2018*/
/* rpm ->        150        350        450        550        750       1000       1250       1500       1750       2000       2500       3000       4000       5000       6000       7000     */
/*load*/
/*  | */
/*  v */
/*    */
/* 1.0 */{    -20.00,    -20.00,     +3.30,     +3.90,     +6.00,     +9.00,    +12.00,    +15.00,    +18.00,    +16.00,    +18.00,    +16.00,    +20.00,    +27.00,    +29.00,    +29.00,    },
/* 1.4 */{    -20.00,    -20.00,    -20.00,     +3.90,     +6.00,    +12.00,    +13.50,    +15.00,    +15.90,    +16.80,    +16.80,    +16.80,    +24.00,    +27.00,    +27.90,    +28.80,    },
/* 1.6 */{    -20.00,    -20.00,    -14.38,     -1.67,     +1.40,     +8.93,    +11.05,    +13.16,    +14.98,    +16.80,    +16.80,    +16.80,    +22.77,    +25.38,    +26.96,    +28.54,    },
/* 1.9 */{    -20.00,    -20.00,     -9.00,     -7.00,     -3.00,     +6.00,     +8.70,    +11.40,    +14.10,    +16.80,    +16.80,    +16.80,    +21.60,    +23.83,    +26.07,    +28.30,    },
/* 2.0 */{    -20.00,    -20.00,     -9.16,     -7.16,     -3.16,     +5.84,     +7.86,     +9.86,    +11.87,    +13.87,    +14.82,    +15.77,    +20.39,    +23.56,    +26.73,    +28.00,    },
/* 2.3 */{    -20.00,    -20.00,     -9.33,     -7.33,     -3.33,     +5.67,     +6.77,     +7.86,     +8.96,    +10.06,    +12.25,    +14.44,    +18.83,    +23.21,    +27.60,    +27.60,    },
/* 2.5 */{    -20.00,    -20.00,     -9.49,     -7.49,     -3.49,     +5.51,     +6.52,     +7.54,     +8.55,     +9.56,    +11.59,    +12.65,    +16.21,    +19.77,    +23.33,    +23.33,    },
/* 2.8 */{    -20.00,    -20.00,     -9.66,     -7.66,     -3.66,     +5.34,     +5.91,     +6.49,     +7.06,     +7.63,     +8.78,     +9.92,    +12.22,    +14.51,    +16.80,    +16.80,    },
/* 2.9 */{    -20.00,    -20.00,     -9.83,     -7.83,     -3.83,     +5.17,     +5.95,     +6.51,     +7.06,     +7.62,     +8.72,     +9.83,    +12.05,    +14.26,    +16.48,    +16.48,    },
/* 3.1 */{    -20.00,    -20.00,    -10.00,     -8.00,     -4.00,     +5.00,     +6.02,     +6.54,     +7.06,     +7.59,     +8.63,     +9.67,    +11.75,    +13.83,    +15.91,    +15.91,    },
/* 3.3 */{    -20.00,    -20.00,    -10.16,     -8.16,     -4.16,     +4.84,     +6.09,     +6.58,     +7.07,     +7.56,     +8.53,     +9.50,    +11.45,    +13.40,    +15.35,    +15.35,    },
/* 3.5 */{    -20.00,    -20.00,    -10.33,     -8.33,     -4.33,     +4.67,     +6.17,     +6.62,     +7.07,     +7.52,     +8.43,     +9.33,    +11.14,    +12.95,    +14.76,    +14.76,    },
/* 3.8 */{    -20.00,    -20.00,    -10.50,     -8.50,     -4.50,     +4.50,     +6.24,     +6.66,     +7.07,     +7.49,     +8.33,     +9.17,    +10.84,    +12.52,    +14.19,    +14.19,    },
/* 4.0 */{    -20.00,    -20.00,    -10.66,     -8.66,     -4.66,     +4.34,     +6.31,     +6.69,     +7.08,     +7.46,     +8.23,     +9.00,    +10.55,    +12.09,    +13.63,    +13.63,    },
/* 4.1 */{    -20.00,    -20.00,    -10.79,     -8.79,     -4.79,     +4.21,     +6.36,     +6.72,     +7.08,     +7.44,     +8.16,     +8.88,    +10.32,    +11.76,    +13.20,    +13.20,    },
/* 4.4 */{    -20.00,    -20.00,    -11.00,     -9.00,     -5.00,     +4.00,     +6.36,     +6.72,     +7.08,     +7.44,     +8.16,     +8.88,    +10.32,    +11.76,    +13.20,    +13.20,    },
};



void setMazda_z5_EngineConfiguration(DECLARE_ENGINE_PARAMETER_SIGNATURE) {

        // Basic Setup
	engineConfiguration->engineType = MAZDA_Z5;
	setOperationMode(engineConfiguration, FOUR_STROKE_CAM_SENSOR);
	engineConfiguration->specs.cylindersCount = 4;
	engineConfiguration->specs.displacement = 1.5;
	engineConfiguration->specs.firingOrder = FO_1_3_4_2;
	engineConfiguration->rpmHardLimit = 6500;

        // Cooling
	engineConfiguration->fanOffTemperature = 95;
	engineConfiguration->fanOnTemperature = 99;
	
        // Cranking
	engineConfiguration->crankingInjectionMode = IM_SIMULTANEOUS;
	engineConfiguration->cranking.rpm = 600;
	engineConfiguration->cranking.baseFuel = 2.5;

        // Trigger
	engineConfiguration->trigger.type = TT_MAZDA_Z5;


	// Ignition 
	engineConfiguration->ignitionMode = IM_ONE_COIL; //distributor
        copyTimingTable(mazda_z5_ign_advance_table, config->ignitionTable);



	// Fuel
	engineConfiguration->fuelAlgorithm = LM_REAL_MAF;
	engineConfiguration->injector.flow = 178;  // manual says -> range 156-200
	// cranking fuel see cranking section


	// stock sensors parameters
	engineConfiguration->tpsMin = 80;
	engineConfiguration->tpsMax = 764;
	setCommonNTCSensor(&engineConfiguration->iat);
	setThermistorConfiguration(&engineConfiguration->iat, -20, 16513, 20, 2450, 80, 315); // last 4 values from handbook , first ones i used beta3540 and magic
	setCommonNTCSensor(&engineConfiguration->clt);
	setThermistorConfiguration(&engineConfiguration->clt, -20, 14970, 20, 2450, 80, 350);// last 4 values from handbook , first ones i used beta3358 and magic
        boardConfiguration->afr_type = ES_NarrowBand;
        setMazda_z5_Maf(config);
        setNarrowToWideAproxTable(PASS_ENGINE_PARAMETER_SIGNATURE);

        // how to drive the outputs
	boardConfiguration->fanPinMode = OM_DEFAULT;  // lowside driver drives relais

	// boardconfig
	engineConfiguration->clt.config.bias_resistor = 3300;
	engineConfiguration->iat.config.bias_resistor = 3300;
	boardConfiguration->ignitionPinMode = OM_INVERTED; // my board has big pullup at prototyping space
	engineConfiguration->vbattAdcChannel = EFI_ADC_14;
        engineConfiguration->vbattDividerCoeff = ((float) (13));
	boardConfiguration->joystickCenterPin = GPIOD_10;
	boardConfiguration->joystickAPin = GPIOD_0;
	boardConfiguration->joystickBPin = GPIOC_8;
	boardConfiguration->joystickCPin = GPIOD_2;
	boardConfiguration->joystickDPin = GPIOD_11;
        boardConfiguration->triggerSimulatorPins[1] = GPIO_UNASSIGNED;
        boardConfiguration->triggerSimulatorPins[2] = GPIO_UNASSIGNED;

/**
 *      pin names:
	GPIOA_0 to GPIOA_7 = EFI_ADC_0 to EFI_ADC_7
	B0 to 1 = 8 to 9
	C0 to 5 = 10 to 15
	maybe put yust GPIO___ in?
 */
	//  Wiring
	//
	//  This is the wiring is on my board and fits only to my personal modified harness!
	//
	//  Change the pins by depin-ing your connector.
	//  Depinning is really conveniant if you have the right little screwdriver.
	//  Has to be really small in diameter. 
	boardConfiguration->triggerInputPins[0] = GPIOA_5; 
	boardConfiguration->triggerInputPins[1] = GPIOC_6; 
	engineConfiguration->tpsAdcChannel  = EFI_ADC_2;
	engineConfiguration->mafAdcChannel  = EFI_ADC_0;
        engineConfiguration->map.sensor.hwChannel = EFI_ADC_NONE;
	engineConfiguration->clt.adcChannel = EFI_ADC_12;
	engineConfiguration->iat.adcChannel = EFI_ADC_11;
        engineConfiguration->afr.hwChannel  = EFI_ADC_13;
	boardConfiguration->ignitionPins[0] =  GPIOE_6;
	boardConfiguration->ignitionPins[1] =  GPIO_UNASSIGNED;
	boardConfiguration->ignitionPins[2] =  GPIO_UNASSIGNED;
	boardConfiguration->ignitionPins[3] =  GPIO_UNASSIGNED;
	boardConfiguration->injectionPins[0] = GPIOB_9;
	boardConfiguration->injectionPins[1] = GPIOD_5;
	boardConfiguration->injectionPins[2] = GPIOB_8;
	boardConfiguration->injectionPins[3] = GPIOB_7;
	boardConfiguration->injectionPins[4] = GPIO_UNASSIGNED;
	boardConfiguration->injectionPins[5] = GPIO_UNASSIGNED;
	boardConfiguration->fanPin = GPIOD_7;
	//boardConfiguration->o2heaterPin = ; need find pin
	boardConfiguration->fuelPumpPin = GPIOC_13;
	boardConfiguration->idle.solenoidPin = GPIOE_2;
        engineConfiguration->brakePedalPin = GPIOA_7;
	for (int i = 0; i < FSIO_ANALOG_INPUT_COUNT ; i++) {
		engineConfiguration->fsioAdc[i] = EFI_ADC_NONE;
	}
        engineConfiguration->baroSensor.hwChannel = EFI_ADC_NONE;
        engineConfiguration->externalKnockSenseAdc = EFI_ADC_NONE;
}
