#!/bin/fish

cd ..

set -e var
for i in (cat autogenerated_list)
     set var $var $i
end

set jarfiles_found (find -type f -name '*.jar')

for i in $jarfiles_found
     set var $var $i
end

git reset -- $var

set suffix  '~origin_master'

for i in (cat autogenerated_list)
    if test -e $i$suffix
        rm $i$suffix
    end
end

for i in $jarfiles_found
    if test -e $i$suffix
        rm $i$suffix
    end
end

cd firmware
